### ISSUE TITLE
WallRun

### ISSUE THREAD

**Issue by rafadsm** [Pantong51/AdvancedMovementComponent#1]
Excellent project, functional at 4.23, any prevision for the wall run?
Dash not visible for blueprints, is it incomplete? Or can I activate and use normally?

**Comment by Pantong51** [comment]
You can activate and use normally. I'll look a bit more into getting more exposed to Blueprint in the next few days.

No wall run yet. Rumors are that 4.24 will have a big rewrite to the replication of this component and I'd like to start from the ground up when that gets released and give binds for using the Gameplay Ability System if wanted.

I've been working on other projects for a while now. But my plans are to revisit this project in the next few weeks to polish it up and cap it off before a 4.24 release.
